CREATE TABLE PRUEBA.IMD_ARQ_CONTINGENCIA
(
     ID NUMBER NOT NULL,
     TIPO_ERROR NUMBER(2) NOT NULL,
     MENSAJE VARCHAR2(4000) NOT NULL,
     FECHA DATE NOT NULL,
     DIRECCION_ENVIO VARCHAR2(1000),
     REENVIADO NUMBER(1),
     ID_MENSAJE VARCHAR2(100)
)
TABLESPACE PRUEBA_TABSPACE;

ALTER TABLE IMD_ARQ_CONTINGENCIA
ADD (CONSTRAINT IMD_ARQ_CONTINGENCIA_PK PRIMARY KEY (ID) using index REVERSE TABLESPACE PRUEBA_TABSPACE );